# Generated by Django 3.2.19 on 2023-05-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=6)),
                ('ticker', models.CharField(max_length=8)),
                ('position', models.CharField(max_length=4)),
                ('date_opened', models.DateField()),
                ('amount_traded', models.DecimalField(decimal_places=2, max_digits=8)),
                ('opening_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('closing_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_closed', models.DateField()),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=8)),
                ('result', models.CharField(max_length=4)),
            ],
        ),
    ]
